%ÉvÉçÉbÉgèÓïÒÇÃîΩâf
function [viewinfo] = localApplyViewInfo(hAxes,viewinfo)
if ~isempty(viewinfo)
     % Set state properties, this will force all corresponding modes
     % to manual
     set(hAxes,'DataAspectRatio',viewinfo.DataAspectRatio,...
             'PlotBoxAspectRatio',viewinfo.PlotBoxAspectRatio,...
             'XLim',viewinfo.XLim,...
             'YLim',viewinfo.YLim,...
             'ZLim',viewinfo.ZLim,...
             'CameraViewAngle',viewinfo.CameraViewAngle,...
             'CameraPosition',viewinfo.CameraPosition,...
             'CameraTarget',viewinfo.CameraTarget,...
             'CameraUpVector',viewinfo.CameraUpVector);
     % Force HG to update internal state of axes by querying.  
     % We could also use a drawnow here, but that will cause
     % a "flash" on the figure window
     %drawnow;
     % Now set mode properties so that any auto modes are building
     % off of previous state.
     
     set(hAxes,'DataAspectRatioMode',viewinfo.DataAspectRatioMode,...
             'PlotBoxAspectRatioMode',viewinfo.PlotBoxAspectRatioMode,...
             'XLimMode',viewinfo.XLimMode,...
             'YLimMode',viewinfo.YLimMode,...
             'ZLimMode',viewinfo.ZLimMode,...
             'CameraViewAngleMode',viewinfo.CameraViewAngleMode,...
             'CameraTargetMode',viewinfo.CameraTargetMode,...
             'CameraUpVectorMode',viewinfo.CameraUpVectorMode);
      
    set(hAxes,'CameraPositionMode',viewinfo.CameraPositionMode);    
    
    % work around for geck 
    set(hAxes,'View',viewinfo.View);  
end
